name: EAS Update

on:
  push:
    branches:
      - main
  workflow_dispatch:
    paths-ignore:
      - 'README.md'
      - 'ios/**'
      - 'android/**'

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: üèó Setup repo
        uses: actions/checkout@v3

      - name: üèó Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: üì¶ Install dependencies
        run: npm ci

      - name: üîç Check Token & Publish
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EAS_NO_VCS: 1
        run: |
          echo "--- DEBUG INFO ---"
          if [ -z "$EXPO_TOKEN" ]; then
            echo "‚ùå ERROR: EXPO_TOKEN variable is EMPTY. Please check GitHub Secrets!"
            exit 1
          else
            echo "‚úÖ EXPO_TOKEN is present in env (Length: ${#EXPO_TOKEN} chars)"
          fi
          
          echo "--- LOGGING IN ---"
          npx eas-cli whoami
          
          echo "--- PUBLISHING TO PRODUCTION ---"
          npx eas-cli update --channel production --message "${{ github.event.head_commit.message }}" --auto
